rs<-rvmises(20)
Rs<-genR(rs)
Qs<-genR(rs,space='Q4')
EAs<-genR(rs,space='EA')

context("Estimators")
expect_that(mean(Rs),is_a("SO3"))
expect_that(mean(Rs,type='intrinsic'),is_a("SO3"))
expect_that(median(Rs),is_a("SO3"))
expect_that(median(Rs,type='intrinsic'),is_a("SO3"))

expect_that(mean(Qs),is_a("Q4"))
expect_that(mean(Qs,type='intrinsic'),is_a("Q4"))
expect_that(median(Qs),is_a("Q4"))
expect_that(median(Qs,type='intrinsic'),is_a("Q4"))

expect_that(mean(EAs),is_a("EA"))
expect_that(mean(EAs,type='intrinsic'),is_a("EA"))
expect_that(median(EAs),is_a("EA"))
expect_that(median(EAs,type='intrinsic'),is_a("EA"))